# Generated by Django 5.1.6 on 2025-02-13 06:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(choices=[('Company A', 'Company A'), ('Company B', 'Company B'), ('Company C', 'Company C')], max_length=100)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst', models.DecimalField(decimal_places=2, default=0, help_text='Enter GST percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('email', models.EmailField(max_length=254)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
